### ISSUE TITLE
Missing ingrastructures from "egi.eu"

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-client#58]
# Issue
I cannot list my infrastructure when using the im-client:

## From [IM-Dashboard](https://appsgrycap.i3m.upv.es:31443/im-dashboard/infrastructures):
![image](https://user-images.githubusercontent.com/47473455/91832514-c7f76800-ec45-11ea-992d-2cf28bf56ca5.png)

## From __im_client.py__:
```sh
$ im_client.py list
Secure connection with: https://appsgrycap.i3m.upv.es:31443/im
No Infrastructures.
```
> im client configuration:
```sh
$ cat im_client.cfg 
[im_client]
restapi_url=https://appsgrycap.i3m.upv.es:31443/im
auth_file=auth.dat

$ cat auth.dat 
id = im; type = InfrastructureManager; username = egi.eu; password = ***egi-token***
```

# Expected
Infrastructures listed at [IM-Dashboard](https://appsgrycap.i3m.upv.es:31443/im-dashboard/infrastructures) match the list provided by `im_client.py list`.

**Comment by BorjaEst** [comment]
When debugging inside [im_client.py L710](https://github.com/grycap/im-client/blob/master/im_client.py#L710) , I get the following:

```sh
-> resp.status_code
200
-> resp.json()["uri-list"]
[]
```
It looks the response from the IM at GET(<restapi>/infrastructures) is empty.
However, if it is so, why is it displayed at the IM-Dashboard?

**Comment by micafer** [comment]
The correct IM auth data must be;
```
id = im; type = InfrastructureManager; token = ***egi-access-token***
```

**Comment by BorjaEst** [comment]
It works, thanks
```sh
$ im_client.py list
Secure connection with: https://appsgrycap.i3m.upv.es:31443/im
Infrastructure IDs: 
  29fe9d4e-e06a-11ea-a1f9-d6e124d8b819
```
